Metrics/ClassLength:
  CountComments: true
  Max: 50

Metrics/ModuleLength:
  CountComments: true
  Max: 50

Metrics/MethodLength:
  CountComments: true
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 1

Metrics/BlockNesting:
  Max: 0

Metrics/PerceivedComplexity:
  Max: 1